server.port=${TODO_PORT:7540}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:todo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:todo}
spring.sql.init.mode=always
spring.datasource.hikari.maximum-pool-size=10
todo.password=${TODO_PASSWORD:}
management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
