apiVersion: 1

providers:
  - name: Todo Scheduler
    orgId: 1
    folder: Todo Scheduler
    type: file
    disableDeletion: false
    editable: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards
